services:
  drone-vc-p:
    build: .
    environment:
      API_ID: $API_ID 
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      AUTH_IDS: $AUTH_IDS
      OWNER_ID: $OWNER_ID
      FORCE_SUBSCRIBE_CHANNEL: $FORCE_SUBSCRIBE_CHANNEL
    resources:
      cpu: 1000m
      memory: 3Gi
      
